name: Release

on:
  pull_request:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    permissions:
      contents: write
      packages: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser (PR)
        uses: goreleaser/goreleaser-action@v5
        if: ${{ !startsWith(github.ref, 'refs/tags') }}
        with:
          args: release --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser (Publish Release)
        uses: goreleaser/goreleaser-action@v5
        if: ${{ startsWith(github.ref , 'refs/tags') }}
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
